spring:
  security:
    user:
      name: user
      password: password #  PasswordEncoder.encode(password)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kip
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: kip1234
jwt:
  expiration: 30 #30분
  secretKey: kipsecret장준혁김영광박세종윤지용

fcm:
  certification : kip-fcm-firebase-adminsdk-gm80d-6a9b5bbd58.json

cloud:
  aws:
    s3:
      bucket: kip-s3
    credentials:
      secret-key: 1
      access-key: 1
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
